### ISSUE TITLE
UI/UX 만들기

### ISSUE THREAD

**Issue by Youngpro95** [team-DD2/diceGame#4]

**Comment by Kang-IJ** [comment]
<img width="413" alt="image" src="https://user-images.githubusercontent.com/70733389/183844783-0f60a5e5-d24c-4d44-84fe-fe607251556e.png">

**Comment by Hypark2018** [comment]
![Image](https://user-images.githubusercontent.com/74716303/183849756-cf461190-873a-4962-905c-1466557f5dd7.jpg)

**Comment by Youngpro95** [comment]
다들 넘 고생하셨어요
