### ISSUE TITLE
요구사항 분석

### ISSUE THREAD

**Issue by Youngpro95** [team-DD2/diceGame#5]

**Comment by Dahyeeee** [comment]
기능요구사항

1. roll 버튼을 누르면 주사위가 굴러가고 random 숫자가 나온다.
2. 지금 turn에서 돌린 주사위 합계가 쌓인다.
3. 주사위가 1이 나오면 쌓은 점수를 얻지 못하고 상대방 turn으로 넘어간다.
3. Hold를 누르면 주사위 합계 점수를 얻고 상대방 turn으로 넘어간다.
(turn이 넘어갈 때 화살표가 넘어가는 기능)
4. 최종점수에 먼저 도달한 사람이 이김.
5. 승자가 정해지면 click으로 새로운 게임 다시 시작.
5. 난이도 조절하는 기능.
6. 컴퓨터 게임 속도 조절 기능.
7. 주사위가 굴러가는 속도 조절 기능.
8. 이길 확률 계산하는 기능.

**Comment by Youngpro95** [comment]
요구사항 분석 고생하셨습니다 👍
